import { useEffect, useMemo, useState } from 'react'
import { Bot, BriefcaseBusiness, Coins, Compass, ShieldCheck, Sparkles } from 'lucide-react'
import { LivingGlobe } from './LivingGlobe'
import { ModuleMark } from './ModuleMark'

declare global { interface Window { Telegram?: { WebApp?: { ready(): void; expand(): void; close(): void; HapticFeedback?: { impactOccurred(style: string): void }; initData?: string } } } }

type Tab = 'home' | 'worlds' | 'wallet' | 'aurum' | 'profile'
type Profile = { name: string; balanceTc: number; status: string; progress: number; nextStatus: string; remaining: string; lastAction: string }
const worlds = [['GARD VPN', 'Защита соединения', '99.9%', 'https://gardvpn.is'], ['SENJOR', 'Премиальная мобильность', '7 мин', 'https://senjorio.com'], ['OSGARD BUSINESS', 'Процессы и рост', '360°', 'https://osgardos.com'], ['SUPER DAY', 'Время под контролем', '16 ч', 'https://superday.run'], ['O2 SYSTEM', 'Учёт без слепых зон', '0.0%', 'https://o2system.art'], ['NEW WORLD', 'Создание продукта', '2 мин', 'https://osgardnewworld.com'], ['VANGUARD STUDIO', 'Видимый результат', '2 мин', 'https://osgardvanguard.studio']]
const questions = ['Где я теряю деньги?', 'Что подключить первым?', 'Как заработать TimeCoin?', 'Свой вопрос...']

export default function MiniApp() {
  const [tab, setTab] = useState<Tab>('home')
  const [selected, setSelected] = useState<number | null>(null)
  const [question, setQuestion] = useState(questions[1])
  const [profile, setProfile] = useState<Profile>({ name: 'Партнёр', balanceTc: 0, status: 'Гость', progress: 0, nextStatus: 'Резидент', remaining: '0.50 TC', lastAction: 'Портал OSGARD готов к входу' })
  const greeting = useMemo(() => { const hour = new Date().getHours(); return hour < 6 ? 'Доброй ночи' : hour < 12 ? 'Доброе утро' : hour < 18 ? 'Добрый день' : 'Добрый вечер' }, [])
  useEffect(() => { document.documentElement.style.background = '#0A0705'; const app = window.Telegram?.WebApp; app?.ready(); app?.expand(); if (app?.initData) fetch(`/api/miniapp/profile?initData=${encodeURIComponent(app.initData)}`).then(r => r.ok ? r.json() : null).then(data => data && setProfile(data)).catch(() => undefined) }, [])
  const go = (next: Tab) => { window.Telegram?.WebApp?.HapticFeedback?.impactOccurred('light'); setSelected(null); setTab(next) }
  const answer = question === questions[0] ? 'Начните с O2 SYSTEM: он покажет, где расходы и процессы теряют точность. Затем AURUM соберёт следующий шаг.' : question === questions[2] ? 'TimeCoin начисляется за подтверждённые действия в экосистеме. Доступные условия всегда видны в вашем профиле.' : 'Начните с GARD VPN для защищённой связи. После этого выберите мир, который закрывает самую срочную задачу.'
  return <main className="miniapp"><header className="mini-head"><span>OSGARD</span><small>PRIVATE PORTAL</small></header>
    {tab === 'home' && <section className="mini-home mini-enter"><div className="mini-globe"><LivingGlobe /></div><p className="mini-kicker">ECOSYSTEM · 2026</p><h1>{greeting},<br />{profile.name}.</h1><p className="mini-statusline">Ваш статус: <b>{profile.status}</b></p><div className="mini-balance"><div><span>TIMECOIN</span><strong>{profile.balanceTc.toFixed(2)} <em>TC</em></strong></div><div><span>ПРОГРЕСС</span><strong>{profile.progress}%</strong></div><i><b style={{ width: `${profile.progress}%` }} /></i></div><button className="mini-primary" onClick={() => go('worlds')}>Открыть экосистему</button></section>}
    {tab === 'worlds' && <section className="mini-page mini-enter"><p className="mini-kicker">07 / MODULES</p><h1>Карта<br />экосистемы</h1><p className="mini-lead">Выберите мир, который решает вашу задачу сейчас.</p><div className="world-grid">{worlds.map(([name, copy, metric, url], index) => <button className={selected === index ? 'is-selected' : ''} key={name} onClick={() => { window.Telegram?.WebApp?.HapticFeedback?.impactOccurred('medium'); setSelected(index) }}><ModuleMark index={index} /><span>{name}</span><small>{copy}</small><b>{metric}</b>{selected === index && <a href={url}>Перейти в мир</a>}</button>)}</div></section>}
    {tab === 'wallet' && <section className="mini-page mini-enter"><p className="mini-kicker">TIMECOIN / WALLET</p><h1>Ваше<br />время ценно</h1><div className="coin-scene"><div className="coin-face"><i>TC</i><span>OSGARD</span></div></div><strong className="mini-total">{profile.balanceTc.toFixed(2)} <em>TC</em></strong><p className="wallet-equivalent">Эквивалент: <b>0 месяцев GARD VPN</b><b>0 поездок SENJOR</b></p><div className="progress-block"><span>До {profile.nextStatus}</span><b>{profile.remaining}</b><i><em style={{ width: `${profile.progress}%` }} /></i></div><div className="wallet-actions"><button>Как заработать</button><button>Потратить</button><button>История</button></div></section>}
    {tab === 'aurum' && <section className="mini-page mini-enter"><p className="mini-kicker">AURUM / CONCIERGE</p><h1>Операционный<br />интеллект</h1><div className="aurum-core"><Bot /><i /><i /><i /></div><p className="aurum-intro">Здравствуйте, {profile.name}. Я вижу ваши семь миров. Что хотите узнать?</p><div className="question-list">{questions.map(item => <button className={question === item ? 'is-active' : ''} key={item} onClick={() => { setQuestion(item); window.Telegram?.WebApp?.HapticFeedback?.impactOccurred('medium') }}>{item}<span>+</span></button>)}</div><div className="aurum-answer"><small>AURUM</small><b>{question}</b><p>{answer}</p></div></section>}
    {tab === 'profile' && <section className="mini-page mini-enter"><p className="mini-kicker">PROFILE / STATUS</p><h1>Ваш статус</h1><div className="member-card"><small>OSGARD PRIVATE</small><b>{profile.name.toUpperCase()}</b><span>{profile.status.toUpperCase()}</span><i>TC</i></div><div className="progress-block"><span>Уровень: {profile.status}</span><b>{profile.progress}%</b><i><em style={{ width: `${profile.progress}%` }} /></i><small>До {profile.nextStatus}: {profile.remaining}</small></div><div className="privilege"><span>Сейчас</span><b>Базовый доступ · 1 продукт</b></div><div className="privilege is-next"><span>Откроется у {profile.nextStatus}</span><b>Все 7 продуктов · VIP-поддержка · кэшбэк 5%</b></div><button className="mini-outline">Как ускорить рост?</button></section>}
    <nav className="mini-nav">{[[Compass, 'home', 'Главная'], [BriefcaseBusiness, 'worlds', 'Миры'], [Coins, 'wallet', 'Кошелёк'], [Sparkles, 'aurum', 'AURUM'], [ShieldCheck, 'profile', 'Статус']].map(([Icon, id, label]) => { const ItemIcon = Icon as typeof Compass; return <button className={tab === id ? 'is-active' : ''} onClick={() => go(id as Tab)} key={String(id)}><ItemIcon /><span>{label as string}</span></button> })}</nav>
  </main>
}
